=== Pryred/nfp121-Declippel-Alexis/projet-court/deroulement.dtd
<!ELEMENT partie (coup*, resultat)>
<!ELEMENT coup EMPTY>
<!ATTLIST coup numero CDATA #REQUIRED
               joueur CDATA #REQUIRED
               prise CDATA #REQUIRED>
<!ELEMENT resultat EMPTY>
<!ATTLIST resultat vainqueur CDATA #IMPLIED
                   tricheur CDATA #IMPLIED>

=== Pryred/nfp121-Declippel-Alexis/projet-court/src/deroulement.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partie SYSTEM "deroulement.dtd">
<partie>
  <coup numero="1" joueur="Xavier" prise="2"/>
  <coup numero="2" joueur="Ordinateur" prise="3"/>
  <coup numero="3" joueur="Xavier" prise="3"/>
  <coup numero="4" joueur="Ordinateur" prise="3"/>
  <coup numero="5" joueur="Xavier" prise="1"/>
  <coup numero="6" joueur="Ordinateur" prise="1"/>
  <resultat vainqueur="Xavier"/>
</partie>

=== Pryred/nfp121-Declippel-Alexis/projet-court/deroulement.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partie SYSTEM "deroulement.dtd">
<partie>
  <coup numero="1" joueur="Alice" prise="3"/>
  <coup numero="2" joueur="Bob" prise="2"/>
  <coup numero="3" joueur="Alice" prise="3"/>
  <coup numero="4" joueur="Bob" prise="1"/>
  <coup numero="5" joueur="Alice" prise="3"/>
  <coup numero="6" joueur="Bob" prise="1"/>
  <resultat vainqueur="Alice"/>
</partie>
